name: Deploy to stage

on:
  pull_request:
    branches:
      - DEV
    types: [closed]

jobs:
  create-release:
    name: Create release
    if: ${{ github.event.pull_request.merged }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create deployment artifact
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ${{ github.event.repository.name }}.zip
          exclusions: '*.git* /*node_modules/* .editorconfig /*src/* .eslintrc.json .prettierrc.json gulpfile.js .stylelintrc.json package.json package-lock.json CHANGELOG.md README.md'
      - name: Store artifact for distribution
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.event.repository.name }}.zip
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
      - name: Get Changelog Entry
        id: changelog-reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: CHANGELOG.md
      - name: Create Release
        id: create-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.changelog-reader.outputs.version }}
      - name: Upload release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
  ftp-deploy:
    name: FTP Deploy
    if: ${{ github.event.pull_request.merged }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 70.32.23.102
          username: ${{ secrets.FTP_USER_STAGE }}
          password: ${{ secrets.FTP_PASS_STAGE }}
          server-dir: /wp-content/plugins/ainsys-connector-content/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/node_modules/**
            **/src/**
            CHANGELOG.md
            README.md
            readme.txt