name: dev-deploy

on:
  pull_request:
    branches:
      - DEV
    types: [closed]

jobs:
  build:
    name: Build project
    if: ${{ github.event.pull_request.merged }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 70.32.23.102
          username: kir@ainsys.com
          password: banan184
          server-dir: /wp-content/plugins/ainsys-connector-content/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/node_modules/**
            **/src/**